codecov:

  branches: *

  ci:

    - travis-ci.org

coverage:

  range: 90..100

  round: nearest

  precision: 2

  status:

    project:

      default:

        target: 90% # Fails tests if coverage go below this

comment:

  behavior: default

  layout: header

  require_changes: false # If true, only post the comment if coverage changes
